# Generated by Django 5.2.3 on 2025-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringnumber',
            name='string_number',
            field=models.CharField(default='zero', max_length=200),
            preserve_default=False,
        ),
    ]
