# Generated by Django 5.2 on 2025-07-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_numbers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='id',
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StringNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_number', models.CharField(max_length=200)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_numbers.number')),
            ],
        ),
    ]
