# Generated by Django 5.2.3 on 2025-07-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_numbers', '0002_stringnumber_string_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringnumber',
            name='string_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
